### ISSUE TITLE
Model interface standard

### ISSUE THREAD

**Issue by jamesjwarren** [trailsjs/trailpack-bookshelf#16]
These ORM trailpacks seem to share the same signature for `config` and `schema` methods:
[trailpack-mongoose](https://github.com/trailsjs/trailpack-mongoose)
[trailpack-sequelize](https://github.com/trailsjs/trailpack-sequelize)

```js
static config(app, orm) {}
static schema(app, orm) {}
``` 

It might be desirable to adopt the same signature here to increase compatibility with other trailpacks that need to work with the model layer? [trailpack-passprt](https://github.com/jaumard/trailpack-passport/issues/138) being one example.

**Comment by jaumard** [comment]
trailpack-waterline also have same signature to have unified interface in order to make compatibility more easy for trailpacks. I think an update is needed here to be compliant.
