### ISSUE TITLE
Deploy on npm

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-bookshelf#7]
@tjwebb can you update travis config file to allow npm deployment ? And also accept https://github.com/trailsjs/trailpack-bookshelf/pull/6  please

Thanks.

**Comment by jaumard** [comment]
@tjwebb little here please, can you update travisCI to deploy on npm. 
Also can you give me rights to manage this repo ?
Thanks

**Comment by jaumard** [comment]
@tjwebb just missing the travis secure key for deploying it on npm :) 
Thanks

**Comment by tjwebb** [comment]
Sorry it took me a couple hours to get to this. Should be set now.
